Unity-Technologies/com.unity.uiwidgets

- .yamato/promotion.yml
- .yamato/upm-ci.yml
- CONTRIBUTING.md.meta
- README-ZH.md.meta
- README.md.meta
- prepare_package.sh
> Add yamato configuration.

- com.unity.uiwidgets/Runtime/async/coroutine.cs
- com.unity.uiwidgets/Runtime/async/microtask_queue.cs
- com.unity.uiwidgets/Runtime/async/priority_queue.cs
- com.unity.uiwidgets/Runtime/async/timer.cs
- com.unity.uiwidgets/Runtime/async2/schedule_microtask.cs
- com.unity.uiwidgets/Runtime/async2/timer.cs
- com.unity.uiwidgets/Runtime/engine2/UIWidgetsPanel.cs
- com.unity.uiwidgets/Runtime/external/RTree.cs
- com.unity.uiwidgets/Runtime/external/SplayTree.cs
- com.unity.uiwidgets/Runtime/foundation/binding.cs
- com.unity.uiwidgets/Runtime/foundation/debug.cs
- com.unity.uiwidgets/Runtime/foundation/isolates.cs
- com.unity.uiwidgets/Runtime/gestures/binding.cs
- com.unity.uiwidgets/Runtime/gestures/multidrag.cs
- com.unity.uiwidgets/Runtime/gestures/multitap.cs
- com.unity.uiwidgets/Runtime/gestures/recognizer.cs
- com.unity.uiwidgets/Runtime/scheduler2/binding.cs
- com.unity.uiwidgets/Runtime/services/asset_bundle.cs
- com.unity.uiwidgets/Runtime/services/binary_messenger.cs
- com.unity.uiwidgets/Runtime/services/binding.cs
- com.unity.uiwidgets/Runtime/ui2/painting.meta
- com.unity.uiwidgets/Runtime/ui2/window.cs
> fix simple compilation errors

- com.unity.uiwidgets/Runtime/animation/listener_helpers.mixin.gen.cs
- com.unity.uiwidgets/Runtime/animation/listener_helpers.mixin.njk
- com.unity.uiwidgets/Runtime/foundation/assertions.cs
- com.unity.uiwidgets/Runtime/foundation/binding.cs
- com.unity.uiwidgets/Runtime/foundation/change_notifier.cs
- com.unity.uiwidgets/Runtime/foundation/diagnostics.cs
- com.unity.uiwidgets/Runtime/foundation/object.cs
- com.unity.uiwidgets/Runtime/foundation/observer_list.cs
- com.unity.uiwidgets/Runtime/foundation/print.cs
- com.unity.uiwidgets/Runtime/gestures/binding.cs
- com.unity.uiwidgets/Runtime/gestures/pointer_signal_resolver.cs
- com.unity.uiwidgets/Runtime/gestures/recognizer.cs
- com.unity.uiwidgets/Runtime/painting/image_provider.cs
- com.unity.uiwidgets/Runtime/painting/image_stream.cs
- com.unity.uiwidgets/Runtime/rendering/box.cs
- com.unity.uiwidgets/Runtime/rendering/debug_overflow_indicator.cs
- com.unity.uiwidgets/Runtime/rendering/flex.cs
- com.unity.uiwidgets/Runtime/rendering/layer.cs
- com.unity.uiwidgets/Runtime/rendering/object.cs
- com.unity.uiwidgets/Runtime/rendering/sliver.cs
- com.unity.uiwidgets/Runtime/scheduler2/binding.cs
- com.unity.uiwidgets/Runtime/scheduler2/ticker.cs
- com.unity.uiwidgets/Runtime/services/binding.cs
- com.unity.uiwidgets/Runtime/widgets/binding.cs
- com.unity.uiwidgets/Runtime/widgets/debug.cs
- com.unity.uiwidgets/Runtime/widgets/framework.cs
- com.unity.uiwidgets/Runtime/widgets/image.cs
I temporarily fix some compile errors under other folders due to unmatched API calls to foundation/scheduler. feel free to fix them when upgrading those files
> upgrade files under foundation&scheduler to match flutter 1.17.5

- com.unity.uiwidgets/Runtime/material/button.cs
- com.unity.uiwidgets/Runtime/material/ink_decoration.cs
- com.unity.uiwidgets/Runtime/material/ink_highlight.cs
- com.unity.uiwidgets/Runtime/material/ink_ripple.cs
- com.unity.uiwidgets/Runtime/material/ink_splash.cs
- com.unity.uiwidgets/Runtime/material/ink_well.cs
> upgrade ink stuffs

- com.unity.uiwidgets/Runtime/gestures/binding.cs
this line is problematic (cause scoll input assertion failures) and not existing in flutter. remove it might be ok?
> fix scroll assertion error

- com.unity.uiwidgets/Runtime/widgets/navigator.cs
> fix navigation error

- com.unity.uiwidgets/Runtime/painting/image_stream.cs
- com.unity.uiwidgets/Runtime/rendering/image.cs
- com.unity.uiwidgets/Runtime/rendering/layer.cs
- com.unity.uiwidgets/Runtime/rendering/view.cs
- com.unity.uiwidgets/Runtime/ui/compositing.cs
- com.unity.uiwidgets/Runtime/ui/native_bindings.cs
- com.unity.uiwidgets/Runtime/ui/painting.cs
- com.unity.uiwidgets/Runtime/widgets/widget_inspector.cs
Reverts Unity-Technologies/com.unity.uiwidgets#179
> Revert "fix: app crash because of animating gif"

- com.unity.uiwidgets/Runtime/painting/alignment.cs
- com.unity.uiwidgets/Runtime/rendering/tweens.cs
static methods in C# cannot be overwrite (which is possible in dart). This pr fixes this issue
> fix stackoverflow

- com.unity.uiwidgets/Editor/UIWidgetsEditorPanel.cs
https://answers.unity.com/questions/1244017/error-sound-on-key-input-editorwindow-ongui.html
> fix editorwindow keyboard event error sound

- com.unity.uiwidgets/Runtime/painting/text_style.cs
This PR fixes a bug that cause incorrect rendering result of text background color
> text background color bug fix

- com.unity.uiwidgets/Runtime/engine/UIWidgetsPanel.cs
cache RawTouch and dispatch during Input_Update
> cache RawTouch and dispatch during Input_Update

- com.unity.uiwidgets/Runtime/painting/text_style.cs
This PR aims to fix the issue reported in #281
> fix text shadow issue

- Samples/UIWidgetsSamples_2019_4/Assets/WidgetsSample/BackdropFilterSample.cs
- Samples/UIWidgetsSamples_2019_4/Assets/WidgetsSample/BackdropFilterSample.cs.meta
- com.unity.uiwidgets/Runtime/rendering/layer.cs
This PR aims to help fix the issue reported in #277
> fix typo in assertion and add a backdropfilter sample

- com.unity.uiwidgets/CHANGELOG.md
- com.unity.uiwidgets/Runtime/rendering/object.cs
- com.unity.uiwidgets/Runtime/rendering/proxy_box.cs
- com.unity.uiwidgets/Runtime/widgets/basic.cs
This PR aims to fix the issue reported in #276
> fix transform hover issue

- Samples/UIWidgetsSamples_2019_4/Assets/UIWidgetsGallery/demo/material/date_and_time_picker_demo.cs
- Samples/UIWidgetsSamples_2019_4/Assets/UIWidgetsGallery/gallery/demos.cs
- com.unity.uiwidgets/Runtime/material/pickers/calendar_date_picker.cs
- com.unity.uiwidgets/Runtime/material/pickers/date_utils.cs
- com.unity.uiwidgets/Runtime/material/pickers/input_date_picker.cs
- com.unity.uiwidgets/Runtime/material/time_picker.cs
This PR aims to fix the issue reported in #280
> bug fix on material datetime picker widget

- com.unity.uiwidgets/Runtime/material/material.cs
- com.unity.uiwidgets/Runtime/material/popup_menu.cs
> fix material issue

- com.unity.uiwidgets/Runtime/ui/painting.cs
This PR fixes the issue reported in #301
> fix path metric crash issue

- com.unity.uiwidgets/Runtime/gestures/multitap.cs
- com.unity.uiwidgets/Runtime/gestures/recognizer.cs
This PR fix a bug that double tap won't be properly triggered
> fix double tap bug

- com.unity.uiwidgets/Runtime/Plugins/Android/arm64/libUIWidgets.so
- com.unity.uiwidgets/Runtime/Plugins/Android/libUIWidgets.so
- engine/Build.bee.cs
- engine/src/shell/platform/unity/android/uiwidgets_panel.cc
- engine/src/shell/platform/unity/android/unity_external_texture_gl.cc
- engine/src/shell/platform/unity/android/unity_external_texture_gl.h
In this PR we add the support of external texture functionalities to android (opengles) platform
> add external texture support to android (opengles)

- com.unity.uiwidgets/Runtime/widgets/scroll_view.cs
In this PR we fix a bug in gridView
> Fix gridView bug

- com.unity.uiwidgets/Runtime/widgets/sliver_persistent_header.cs
In this PR we fixed the bug in #315
> fix sliver persistent header

- com.unity.uiwidgets/Editor/UIWidgetsEditorPanel.cs
This PR aims to add a safeguard on EditorPanel to avoid null object exception
> refine editor side code

- com.unity.uiwidgets/Editor/UIWidgetsEditorPanel.cs
add a overridable API onGUI to developers to track OnGUI calls
> expose onGUI

- com.unity.uiwidgets/Runtime/material/refresh_indicator.cs
> fix refreshIndicator bug

- Samples/UIWidgetsSamples_2019_4/Assets/MaterialSample/FlowSample.cs
- Samples/UIWidgetsSamples_2019_4/Assets/MaterialSample/FlowSample.cs.meta
- com.unity.uiwidgets/Runtime/material/bottom_sheet.cs
- com.unity.uiwidgets/Runtime/rendering/flow.cs
- com.unity.uiwidgets/Runtime/rendering/flow.cs.meta
- com.unity.uiwidgets/Runtime/widgets/basic.cs
In this PR we add back the missing codes as pointed out by #347
> add missing codes for flow and bottomsheet
